import Link from "next/link";
import Providers from "./providers";

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				{/* Wrapping the children in the Providers component provides the session info globally. You can then use getServerSession */}
				<Providers>
					<nav style={{ padding: "5 px 0" }}>
						<Link href="/">Frontpage</Link>
						{` `}
						<Link href="/admin-dashboard">Admin Dashboard</Link>
						{` `}
						<Link href="/profile-page">Profile Page</Link>
					</nav>
					{children}
				</Providers>
			</body>
		</html>
	);
}
